### ISSUE TITLE
Çeviride kullanılacak kelimeler/terimler hakkında açıklama

### ISSUE THREAD

**Issue by hwpplayer1** [ayyucedemirbas/linux-insides_Turkish#3]
Merhaba @ayyucedemirbas ,
Çeviri işi biraz gecikti biliyorum... bir taraftan GNU Emacs ile uğraştım bu arada öğrenmem gereken özellikleri vardı. Markdown preview gibi ... VS Code da kullanıyorum daha pratik diğerinde elle tek tek çevirmem gerekiyor. İkisi de lazım bana... 

En kısa süre içerisinde ilk pull request'i göndereceğim. 

Anlayışınız için teşekkürler,
İyi çalışmalar,
Saygılarımla

**Comment by ayyucedemirbas** [comment]
teşekkürler
