### ISSUE TITLE
TinyPic linkleri kırık.

### ISSUE THREAD

**Issue by 0x1-1** [ayyucedemirbas/linux-insides_Turkish#4]
![image](https://user-images.githubusercontent.com/35432275/87307490-64449e80-c522-11ea-9ef7-c244c129d0fa.png)

[linkte](https://github.com/ayyucedemirbas/linux-insides_Turkish/blob/master/Booting/linux-bootstrap-1.md ) bulunan tinypic linkleri kırık, düzeltebilir misiniz? Teşekkürler.

**Comment by ayyucedemirbas** [comment]
Çok teşekkür ederim. Düzeltildi.
